# Generated by Django 5.0 on 2023-12-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PixelSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_text', models.TextField()),
                ('carrier_image', models.ImageField(upload_to='')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
